### ISSUE TITLE
Resolve the difference in node-operator / building from source

### ISSUE THREAD

**Issue by mkjmdski** [vegaprotocol/documentation#109]
We currently encourage people to run completely different command to build the [binary](https://github.com/vegaprotocol/documentation/blob/main/docs/node-operators/from-source.md#build-the-vega-node) than we have in official [Makefile](https://github.com/vegaprotocol/vega/blob/develop/Makefile#L31). That regards [data node](https://github.com/vegaprotocol/data-node/blob/develop/Makefile#L48) too.

Most open source docs say that you should just run "make build" and then "make install" (if needed). So maybe we should adjust the Makefile and then refer to it in the docs?

**Comment by candida-d** [comment]
Closing after conferring a bit on this - external devs/operators shouldn't need to rely on the makefile, when those things are more geared towards the internal dev team. The simpler solution in this case is probably better!
