### ISSUE TITLE
Missing /data-node section at top level of gRPC documentation

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/documentation#126]
The gRPC documentation currently has one top-level section, `/vega`. However there should be a second one, `/data-node` (included in the [old style docs](https://docs.fairground.vega.xyz/api/grpc/)) which contains a fair amount of information (and is especially useful to anyone external wanting to load data).

![image](https://user-images.githubusercontent.com/702798/176157956-2bebe7c7-fc13-4880-a3c1-970b7af7719d.png)

**Comment by edd** [comment]
Now blocked by #168
