### ISSUE TITLE
Update API docs once the data-node is in the core repo

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/documentation#153]
Blocked until the one or both of the following issues are complete:
- https://github.com/vegaprotocol/vega/issues/5613
- https://github.com/vegaprotocol/vega/issues/5011

When the data-node and protos are moved back into the core vega repo the API documentation will need to be updated:

Most of not all of the API reference (generated) documentation routing will need to change (it has to be set up to be possible to do this this time around):

- [ ] change all the open API config in docusaurus and the build script.

**Comment by gordsport** [comment]
Whoever picks this issue up may wish to consult @candida-d for further direction on what is required

**Comment by gordsport** [comment]
Hey @edd 
Is this issue a duplicate pf the work you have been doing?

**Comment by edd** [comment]
@gordsport It's a better ticket for what I've been doing, which isn't really ticketed 😆 

This is complete in #194 - not merged, but will be close by this.
