### ISSUE TITLE
Node docs: Ethereum key rotation

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#163]
The node operators documentation needs a guide for how to do Eth key rotation.

**Comment by karlem** [comment]
This is currently block due to change in multisig bundle generation that will need to be reflected in the docs. The change is being worked on by core team this sprint.

**Comment by wwestgarth** [comment]
Just a heads up that the process will change a little as a result of: 
https://github.com/vegaprotocol/vega/issues/6271
https://github.com/vegaprotocol/vega/issues/6291

but I'll happily make the required changes.

**Comment by candida-d** [comment]
Thanks @wwestgarth! The docs aren't blocked anymore, @karlem has written docs so you can edit here when the time is right: https://github.com/vegaprotocol/documentation/pull/189/files#diff-efd2e0cc8e108bc7e042e76a584c162011482765ba2c7de037079e3535b00502
