### ISSUE TITLE
Update Propose New Market tutorial to include IPFS link & hash 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/documentation#172]
At tutorial here: 

https://docs.vega.xyz/docs/testnet/tutorials/proposals/new-market-proposal

The proposal only contains free text rationale. 

Since then there have been updated to now expect the URL and hash from IPFS where this rationale is stored.  

Page needs to be updated to reflect this (similar to freeform proposal)

**Comment by edd** [comment]
Not changing for now
