### ISSUE TITLE
Inline link styles on page body are not noticeable

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/documentation#18]
light mode: this "relseaes" word needs a link style
<img width="892" alt="Screenshot 2021-11-18 at 15 22 00" src="https://user-images.githubusercontent.com/13255539/142444444-620cbba6-aaca-41d9-b30e-fa8a5ecd3030.png">

dark mode: the link colour is same as background

<img width="893" alt="Screenshot 2021-11-18 at 15 22 05" src="https://user-images.githubusercontent.com/13255539/142444507-1d56ba6b-7c8c-4f90-ad02-ad2287a0a852.png">

**Comment by candida-d** [comment]
Related: Link styles are inconsistent across the site and in different situations 

https://user-images.githubusercontent.com/62548908/142457225-ae114ecb-75a0-4891-a30c-963462d2bf9e.mov

**Comment by candida-d** [comment]
For now I've made it a brand color that juuust about works in dark and light modes but making the font colors different for dark vs light is beyond my capabilities.

**Comment by candida-d** [comment]
@campbellssource I made the change on the https://github.com/vegaprotocol/documentation/tree/network-treasury branch

**Comment by candida-d** [comment]
Closing this (for now) as I've replaced it (in the branch) with a brand color that works for both light and dark mode, and we can revisit more exciting styling options in the future
