### ISSUE TITLE
Incorporate new wallet API docs 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#183]
Once https://github.com/vegaprotocol/vega/pull/5815 and https://github.com/vegaprotocol/vega/pull/5824 are done (and released) there will be documentation for the new wallet API. 

- [ ] Create getting-started guide for using the wallet API
- [ ] Incorporate the documentation into scripts/etc so that it can generate per release
- [ ] Add to API docs section

**Comment by edd** [comment]
https://github.com/open-rpc/docs-react Will be useful!
