### ISSUE TITLE
Link to staking reward spec is incorrect

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#193]
On the page [https://docs.vega.xyz/docs/mainnet/concepts/vega-chain#rewards](https://docs.vega.xyz/docs/mainnet/concepts/vega-chain#rewards) the link for "further reading" to the "staking reward spec" is broken (the specs repo URL changed). 

<img width="1120" alt="Screenshot 2022-08-15 at 12 09 45" src="https://user-images.githubusercontent.com/46783148/184627532-27c6cc07-00d3-43ea-adc2-88339c481783.png">

**Comment by candida-d** [comment]
This is working for me and @ckpringle, so I'm going to close
