### ISSUE TITLE
Include risk model section in the market creation tutorial and include leverage details

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#207]
In the market creation tutorial:

How might we describe how the risk model selected effects leverage?

During the market creation incentive, participants were asking: 
- Can we limit the amount of leverage possible?
- Does the choice of parameters of the risk model affect the leverage ratio chosen?. I don’t understand the risk model very well.
- How do I check leverage level?
- What is the maximum leverage for this market looking at the risk model?

**Comment by JonRay15** [comment]
This is pretty complex I believe....basically some combination of these equals max leverage.

logNormal: {
tau: 0.0001140771161,
riskAversionParameter: 0.01,
params: {
mu: 0,
r: 0.016,
sigma: 0.8
}}

I believe David has a spreadsheet that modelled this, I wonder if there's some way we can expose this via the docs?

**Comment by barnabee** [comment]
`leverage = 1 / risk_factor` and you can get the risk factor from the API for an extant market:
```
query {
  market(id: "b3ed2767848b86240224526986fc98b134e9e3e82e123b7dec6e8315f9df41ea") {
    id, name
    riskFactors { long, short }
  }
}

{
  "data": {
    "market": {
      "id": "b3ed2767848b86240224526986fc98b134e9e3e82e123b7dec6e8315f9df41ea",
      "name": "Apple Monthly (30 Jun 2022)",
      "riskFactors": {
        "long": "0.0085081329932736",
        "short": "0.0085717903672853"
      }
    }
  }
}
```

So that has leverage of 117.5x by the looks of it 🤠 

Calculating the risk factor from the risk model plus params is harder, though. [This spreadsheet](https://docs.google.com/spreadsheets/d/1pAEPPcIMzI-dDEkIKgfU6xMuVR9xnChs) can help, it'll show you the risk factors and leverage.

**Comment by JonRay15** [comment]
Have also just noticed we actually dont have a sub-heading for the risk model in general ... I think we need to add a section here to explain those parameters, and ideally work out how we can make David's spreadsheet available via the docs so that people can experiment.

**Comment by JonRay15** [comment]
Final thinking on this with Barney before I left the office was maybe actually the easiest thing to do here is to include a table of example risk models which lead to various values for the max leverage, along with some explanation of how to select an appropriate one. 

We could leave it open to users to ignore the examples and choose their own custom risk model, but state that to do so implies a need to justify that model as part of making the market proposal.  Ultimately we want the process to imply a higher burden of proof the more aggressive the risk model chosen, down to an almost non-existent burden of proof for a 1 max leverage.

I think I can pick this one up as it doesnt involve any tech stuff with the docs pages,
