### ISSUE TITLE
Link to proposing a new settlement asset as a part of market creation tutorial

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#210]

**Comment by ckpringle** [comment]
How might we link to proposing a new settlement asset as a part of choosing your asset (when it's available) so that people can create a market with whatever settlement asset they want at the time they need to.

**Comment by candida-d** [comment]
I wouldn't expect that most people who want to create a market would want to also create an asset, and proposers need to do a lot of pre-work before getting to this stage, so I'm not convinced that a link in the middle of this tutorial is the right thing.
