### ISSUE TITLE
Various minor tweaks to market creation tutorial

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/documentation#214]
How might we do more to answer these questions in the docs and make it easier to find the answers? (attached)

- Check through the list to see what does or doesn't exist 
- Identify any quick wins to improve find-ability / visibility (I wondered if we might have an FAQ section or something?) 

Will review other open questions from the incentive and raise a PR with proposed changes to the market creation tutorial as discussed. 

![Screenshot_20230227_173616](https://user-images.githubusercontent.com/89918817/221640462-1af34be0-f552-43a7-827a-1d96359a6e00.png)
![Screenshot_20230227_173629](https://user-images.githubusercontent.com/89918817/221640477-456473b8-68ff-45c4-8179-5644fef1da5b.png)
![Screenshot_20230227_173639](https://user-images.githubusercontent.com/89918817/221640492-416ddd30-d1ae-4533-8e19-22e585edb716.png)

**Comment by pennyandrews** [comment]
@neildawson Jon is keen to help with this but might need a wee crash course in how to create PRs in github and maybe some support with the work itself too. Might be something you could pair on?
