### ISSUE TITLE
Network parameter component targets are case sensitive

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/documentation#223]
When embedding a network parameter component, the target network parameter must be defined exactly as shown in [this list](https://lb.testnet.vega.xyz/network/parameters) (thanks Edd for this link!).

This tripped me up, as the parameters are listed with different capitalisation on [the Block Explorer network parameters page](https://explorer.fairground.wtf/network-parameters).

For example, note the difference in capitalisation of the `param` field in these examples.

This code will pull in the parameter values successfully:
`<NetworkParameter frontMatter={frontMatter} param="reward.staking.delegation.optimalStakeMultiplier" />`

This code will **_not_** pull in the values:
`<NetworkParameter frontMatter={frontMatter} param="Reward.Staking.Delegation.OptimalStakeMultiplier" />`

It may be helpful to provide an error state when the parameter is unrecognised. By default, the component will print whatever you write in the param field, so at a glance you might think it is properly defined.

**Comment by edd** [comment]
Spoke to @candida-d about this - given the network parameters are mixed case, we're going to leave it as is. However it should HANDLe it better.
