### ISSUE TITLE
Diagram of validator statuses, journey between them

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#260]
Visualisation of the journey from candidate to consensus validator for [the rewards page](https://deploy-preview-189--vega-docusaurus.netlify.app/docs/testnet/node-operators/rewards). Could be useful on the vega.xyz validators page, too.

**Comment by neildawson** [comment]
@candida-d we spoke about the possibility of adding a visual to the Node operators Rewards page, to help people understand the levels and their journey through them. I was reminded of this ticket, so have added it here.

**Comment by candida-d** [comment]
Reworded this ticket to be about the specific diagram, in favour of raising specific issues per diagram.
