### ISSUE TITLE
Transfer asset command line example issue

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/documentation#306]
## Description

Trying to use the Linux/OSX command line for recurring transfers to reward pool but am running in to 2 issues, **firstly** that the script adds dispatchmetric, but trying to run the command with this results in an error, `couldn't unmarshal command as request: unknown field "dispatchMetric" in vega.DispatchStrategy` instead "metric" should be used. 

**Secondly** having a short comment about what "assetForMetric" is would be useful since the place it is is mentioned is https://docs.vega.xyz/docs/testnet/grpc/vega/vega.proto#dispatchstrategy but that only says "The asset to use for metric", not sure if that is clear, maybe it is just me.

## Steps to Reproduce First issue! _(note that I have removed the marketID in the command)_
<img width="892" alt="Screenshot 2022-10-04 at 13 33 22" src="https://user-images.githubusercontent.com/100769129/193809555-bfc8490a-a36b-4143-b174-9b7801819050.png">

1. Go to https://docs.vega.xyz/docs/testnet/tutorials/transferring-assets#recurring-transfer-to-vega-key
2. Click on copy Linux / OSX command line and copy code
3. Paste in terminal using the latest wallet **0.57**
```
vegatestwallet ./vegawallet command send --wallet "test" --pubkey "476fc2843ba2d64aa1c73a1e1b7215843f581cf4d6c8f46587b12b37e27cc8fa" --network fairground --no-version-check '{
    "transfer":{
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "toAccountType": "ACCOUNT_TYPE_REWARD_MAKER_RECEIVED_FEES",
        "to":"0000000000000000000000000000000000000000000000000000000000000000",
        "asset":"b88f6326877464349530fc4e2fdfe2bba343981226ee16edc55d21077cb03boo",
        "amount":"10000000000000000000",
        "recurring":{
            "startEpoch":"988",
            "factor": "2",
            "dispatchStrategy": {
                "assetForMetric": "b88f6326877464349530fc4e2fdfe2bba343981226ee16edc55d21077cb03b12",
                "dispatchMetric": "DISPATCH_METRIC_MAKER_FEES_RECEIVED"
            }
        }
    }
}'
```
✗ couldn't unmarshal command as request: unknown field "dispatchMetric" in vega.DispatchStrategy

## Expected behavior
Enter passphrase: 
And transfer sent

Instead using the following script works:
```
./vegawallet command send --wallet "test" --pubkey "476fc2843ba2d64aa1c73a1e1b7215843f581cf4d6c8f46587b12b37e27cc8oo" --network fairground '{
    "transfer":{
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "toAccountType": "ACCOUNT_TYPE_REWARD_MAKER_RECEIVED_FEES",
        "to":"0000000000000000000000000000000000000000000000000000000000000000",
        "asset":"b88f6326877464349530fc4e2fdfe2bba343981226ee16edc55d21077cb03b12",
        "amount":"10000000000000000000",
        "recurring":{
            "startEpoch":"988",
            "factor": "2",
            "dispatchStrategy": {
                "assetForMetric": "b88f6326877464349530fc4e2fdfe2bba343981226ee16edc55d21077cb03b12",
                "metric": "DISPATCH_METRIC_MAKER_FEES_RECEIVED"
            }
        }
    }
}'
```

**Comment by edd** [comment]
@daunatv https://github.com/vegaprotocol/documentation/pull/313 should work - I've run the updated examples with a local wallet that has no assets, but if you want to give it a shot with a wallet with assets to make sure it works end to end that would help.

If not, let me know and I'll 🤠 it in anyway.

**Comment by daunatv** [comment]
Oh, I will test it out Asap, will test the market as well since that makes sense.

**Comment by edd** [comment]
Thanks for letting me be lazy
