### ISSUE TITLE
Block Explorer API docs not showing in testnet docs site

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/documentation#315]
## The Chore

A block explorer swagger file is created when core tags a version. This is not currently showing in the testnet section of the API docs.

The core side to add the swagger doc is in this PR:

- https://github.com/vegaprotocol/vega/issues/6411

**Comment by edd** [comment]
Note: This was technically *in* 0.57.0 (see: https://github.com/vegaprotocol/documentation/tree/main/specs/v0.57.0) but isn't showing up in the docs site. It wasn't working at the time that version was tagged, so I dropped it. When 0.58.0 is tagged, I'll make sure it shows up and then close this issue.

**Comment by edd** [comment]
Completed in the past, but I forgot to close the ticket 😬 Probably when 0.58.0 released. Definitely fixed in the current deploy (0.60.0)
