### ISSUE TITLE
Eliminate workarounds for API documentation

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#326]
Once alpha mainnet goes live: Reduce/eliminate the number of workarounds in the build scripts for API documentation. This will require collaboration with core to improve pipelines and docs functionality in the vega repo. 

Doing this will mean that generating API documentation won't be reliant on scripts that can go out of date or need to be updated with each new release to account for inconsistencies/missing functionality. 

# Workarounds list
- [ ] [Reorganise spec files created on core tag](https://github.com/vegaprotocol/documentation/blob/main/scripts/build-pre-flatten.sh)
- [ ] [Generate OpenAPI v3 files from Swagger docs](https://github.com/vegaprotocol/documentation/blob/main/scripts/build-pre-flatten.sh)
- [ ] [Not all Swagger docs contain a version number](https://github.com/vegaprotocol/documentation/blob/main/scripts/build-pre-fix-specs.sh#L9)
- [ ] [Multiline summaries in swagger create bad titles](https://github.com/vegaprotocol/documentation/blob/52881cad55f1f7ee688b299d96a7becf3a9d3be2/scripts/build-pre-fix-specs.sh#L13-L14), which also [ends up with us tidying up trailing punctuation](https://github.com/vegaprotocol/documentation/blob/main/scripts/build-pre-fix-specs.sh#L18-L19)
- [ ] [Fix TradingDataService names](https://github.com/vegaprotocol/documentation/blob/main/scripts/build-pre-fix-specs.sh#L22) & [TradingDataService](https://github.com/vegaprotocol/documentation/blob/52881cad55f1f7ee688b299d96a7becf3a9d3be2/scripts/build-pre-fix-specs.sh#L25)
- [ ] [Swagger files contain invalid servers](https://github.com/vegaprotocol/documentation/blob/52881cad55f1f7ee688b299d96a7becf3a9d3be2/scripts/build-pre-fix-specs.sh#L28-L29)
- [ ] Special case for Testnet Block Explorer 

# Why this matters
As we remove these workarounds, we get closer to a point where:
- Spec update PRs can automatically trigger builds
- Generated spec files can be created at build time and not committed, which will lead to less conflicts between PRs
- The spec files will be more useful for other people

**Comment by edd** [comment]
See https://github.com/vegaprotocol/documentation/pull/422 which feels relevant
