### ISSUE TITLE
Add a step to create a validator profile on the forum to "becoming a validator"

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#341]
## Chore 

We want to tie in the use of the forum as a place to publicise intent to become a validator and provide a way to do that from the docs. 

## Tasks 

- [ ] Add creating a profile on the forum https://community.vega.xyz/c/mainnet-validator-candidates/23 to [Becoming a validator](https://docs.vega.xyz/docs/mainnet/concepts/vega-chain#becoming-a-validator) as a way to publicise your intent to become a validator in addition to your other community channels e.g. "Make your case to the community by creating a validator profile on the forum".

**Comment by candida-d** [comment]
This is, in effect, covered in #189
