### ISSUE TITLE
Diagram: Data node

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#388]
Turn the image below into a diagram that can be used in the docs for a high-level overview of the data node architecture. 

![IMG_1984](https://user-images.githubusercontent.com/62548908/201366170-5199043e-c8bf-4e45-bd4e-e81a96b08a90.jpg)

**Comment by gordsport** [comment]
![Data-node-overview (1)](https://user-images.githubusercontent.com/83510148/202037757-0d7c1cf6-641b-4294-a440-d99aea0df375.png)
 
 To align with [this page](https://docs.vega.xyz/testnet/concepts/deposits-withdrawals#diagrams-withdrawals).
 
If required to be in black/white I can update this:
[Data-node-overview.drawio.zip](https://github.com/vegaprotocol/documentation/files/10016598/Data-node-overview.drawio.zip)
