### ISSUE TITLE
How to interact with the wallet service from dApps and bots point-of-view

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#390]
Add lightweight documentation to help people interact with the api v2 library, such as for setting up bots

**Comment by candida-d** [comment]
This would be better done after the API token work is completed

**Comment by ValentinTrinque** [comment]
# From dApps

## 1. Connecting to the service

1. You can verify the service is running with `GET /api/v2/health`
2. If alive, verify the service exposes the methods you rely with ` GET /api/v2/methods`
3. If ok, you can start isuing request to the wallet software with `POST /api/v2/requests`


## 2. Issuing request to the service

_Warning: The service requires the `Origin` (or `Referer`) HTTP header to be specified in the request. This is usually handled by the browser, so you may not have anything to do, but for other software that do not value one of those headers, the request will be rejected._

With`POST /api/v2/requests`, you can talk to the wallet. The request body is a JSON-RPC 2.0 payload.

Refer to JSON-RPC 2.0 standard to know more about JSON-RPC itself: https://www.jsonrpc.org/specification
Refer to the OpenRPC documentation of the wallet for more details about the available methods.

1. Get the chain ID to which the service is connected. This is important so your app can display the information related to the network the service is connected to:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.get_chain_id",
     "id": "request_1"
   }
   ```
2. Once you app display the right data, connect to the wallet:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.connect_wallet",
     "id": "request_2"
   }
   ```
   Wait for user approval. On success you will get a token back. This token will be required to query protected methods. **The token is unique and randomly generated for every connection.**
4. Once connected, list the keys exposed to you:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.list_keys",
     "params": {
       "token": "THE_TOKEN_FROM_THE_CONNECT_WALLET_CALL"
     }
     "id": "request_3"
   }
   ```
5. Once you have access the key list, you can send transaction:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.send_transaction",
     "params": {
        "token": "THE_TOKEN_FROM_THE_CONNECT_WALLET_CALL",
        "publicKey": "ONE_OF_THE_PUBLIC_KEY_FROM_THE_LIST_KEY_CALL",
        "sendingMode": "TYPE_SYNC",
        "transaction": {
            "voteSubmission": {
                "proposalId": "SOME_PROPOSAL_ID",
                "value": "VALUE_YES"
            }
        }
     },
     "id": "request_4"
   }
   ```
   Wait for the user to approve the transaction. _Note, The `transaction` field is an example._
6. _Optional_, but we recommend to expose a disconnection button:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.disconnect_wallet",
     "params": {
       "token": "THE_TOKEN_FROM_THE_CONNECT_WALLET_CALL"
     }
     "id": "request_5"
   }
   ```


# For headless software (bots, for example)

## 1. Generate a long-living token

1. Enable the support for the long-living tokens of the service:
   ```bash
   vegawallet api-token init
   ```
   This is only needed once, for the first time you are using long-living tokens.
2. Generate a token, and linked it to the wallet of your choice:
   ```bash
   vegawallet api-token generate --wallet-name "my-wallet" --description "for my trading bot"
   ```
3. Start the service **with the long-living token support**:
   ```bash
   vegawallet service run --load-tokens --network testnet1
   ```
   If you forget the `--load-tokens` flag, the sessions with long-living tokens are not created.

## 2. Connecting to the service

1. You can verify the service is running with `GET /api/v2/health`
2. If alive, verify the service exposes the methods you rely with ` GET /api/v2/methods`
3. If ok, you can start isuing request to the wallet software with `POST /api/v2/requests`

## 3. Issuing request to the service

_Warning: The service requires the `Origin` (or `Referer`) HTTP header to be specified in the request. This is usually handled by the browser, so you may not have anything to do, but for other software that do not value one of those headers, the request will be rejected._

With`POST /api/v2/requests`, you can talk to the wallet. The request body is a JSON-RPC 2.0 payload.

Refer to JSON-RPC 2.0 standard to know more about JSON-RPC itself: https://www.jsonrpc.org/specification
Refer to the OpenRPC documentation of the wallet for more details about the available methods.

**You don't need to connect. You can use the pre-generated, long-living token in place of the regular token.**

1. List the keys exposed to you:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.list_keys",
     "params": {
       "token": "THE_LONG_LIVING_TOKEN"
     }
     "id": "request_1"
   }
   ```
2. Once you have access the key list, you can send transaction:
   ```json
   {
     "jsonrpc": "2.0",
     "method": "client.send_transaction",
     "params": {
        "token": "THE_LONG_LIVING_TOKEN",
        "publicKey": "ONE_OF_THE_PUBLIC_KEY_FROM_THE_LIST_KEY_CALL",
        "sendingMode": "TYPE_SYNC",
        "transaction": {
            "voteSubmission": {
                "proposalId": "eb2d3902fdda9c3eb6e369f2235689b871c7322cf3ab284dde3e9dfc13863a17",
                "value": "VALUE_YES"
            }
        }
     },
     "id": "request_4"
   }

Contrary to the regular connection token, long-living tokens are highly privileged tokens that bypass user review and approval process.
