### ISSUE TITLE
Reference triggering ratio on market protection 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#394]
Liquidity auction section should mention how the triggering auction can effect if a market enters into an auction, and add link to liq page

**Comment by daunatv** [comment]
Should add a "," comma in the command for order
<img width="765" alt="Screenshot 2022-12-04 at 15 58 36" src="https://user-images.githubusercontent.com/100769129/205498043-fd7a293c-b318-42f0-9318-775b6f35d694.png">
<img width="765" alt="Screenshot 2022-12-04 at 15 59 53" src="https://user-images.githubusercontent.com/100769129/205498296-3cc682b0-8c2b-4cce-9a95-5f1a178ac5b2.png">
