### ISSUE TITLE
Tutorial: Build a basic market maker bot (limit orders and batch instructions)

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#403]
## Background

![Image](https://user-images.githubusercontent.com/46783148/227514707-13ed48db-bfcd-4334-8fee-d3c7ec68aed2.png)

![Image](https://user-images.githubusercontent.com/46783148/227514821-a19bc4f9-e102-426b-bc0c-54fd46e149eb.png)

**Comment by rebeccajsimmonds** [comment]
@TomMcL picking this up from @MM0819 @TomMcL let us know what you need

**Comment by TomMcL** [comment]
Similar to my liquidity question, does [this](https://docs.vega.xyz/testnet/tutorials/programmatic-trading-basics#set-up-your-vega-wallet) cover enough that just a companion video going through that setup and maybe a bit about the Python MM code would do the trick? Or do we need a further tutorial?
