### ISSUE TITLE
Tutorial: Manage a Liquidity order via the APIs

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#406]
question: does this replace the existing one, or do they coexist?

## Background 

![Image](https://user-images.githubusercontent.com/46783148/227514986-b4b11e40-4dea-4b5e-b4d5-f11299060a3e.png)

![Image](https://user-images.githubusercontent.com/46783148/227515154-d2a16c54-20ef-4172-a4a5-dd3c44b6277d.png)

**Comment by rebeccajsimmonds** [comment]
After discussion with @MM0819 and @TomMcL Tom has agreed to pick this up. He may need some brief @pennyandrews - not sure if you can either do that or whether @MM0819 does it?

**Comment by candida-d** [comment]
> After discussion with @MM0819 and @TomMcL Tom has agreed to pick this up. He may need some brief @pennyandrews - not sure if you can either do that or whether @MM0819 does it?

@rebeccajsimmonds, @MM0819 had a vision for what these tutorials could provide, but if he's not available I can probably provide enough background to go on.

**Comment by TomMcL** [comment]
What do we think is missing from a text tutorial which is not already covered pretty well [here](https://docs.vega.xyz/testnet/tutorials/committing-liquidity#creating-a-liquidity-commitment)? Or do we just want a video in addition?

**Comment by candida-d** [comment]
Done in #487
