### ISSUE TITLE
Explain how to integrate the wallet service in a CI/CD

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/documentation#417]
This can be useful for dApps devs that want to work with the wallet.

This is a guide how to set up  from scratch and use Vega Wallet for Vega dApps. You can find current working CI/CD implementation [here](https://github.com/vegaprotocol/frontend-monorepo/blob/develop/.github/actions/setup-vegawallet/action.yml). Some steps may be skipped - api-token related steps are needed only for E2E and CI/CD integration. Also, if you already have Vega wallet prepared and configured, you will probably need only the last step to run the wallet.

1. Create two files: `passphrase` and `recovery` - `passphrase` will be used as a wallet and api-token password (you may want to use two different ones), and `recovery` should contain recovery phrase of the wallet you want to use (you may skip it if you don’t have one yet, and want to create a new one.
2. Download and install Vega wallet. There are two ways to do that:
    1. Download the latest release of [Vega](https://github.com/vegaprotocol/vega/releases) and unzip it to some shared location. To test if it worked you may run `vega version` command.
    2. Clone [Vega repo](https://github.com/vegaprotocol/vega). Make sure you have installed `go` (`1.19` version required at the time of writing this document). Setup `GOBIN` env and add it to `PATH` (e.g. `export GOBIN="$HOME/go/bin; export PATH=$GOBIN/:$PATH`. Run `go install ./…` to install binaries. Verify by running `vega version` command.
3. Initialise a wallet - `vega wallet init -f --home <WALLET_PATH>` - this one creates new, fresh wallet files. 
`--home <WALLET_PATH>` sets wallet location. You can skip it if you want to use default location, you should skip it in all other steps as well then. 
`-f` flag overwrites existing wallet configuration at the location. 
4. Create new or import existing wallet (you may create/import as many wallets as you want).
    1. New wallet: `vega wallet create -w <WALLET_NAME> -p passphrase --home  <WALLET_PATH>`
    2. Import the wallet using recovery phrase:  `vega wallet import -w <WALLET_NAME> --recovery-phrase-file recovery -p passphrase --home <WALLET_PATH>`.
5. You may create additional public keys if you need - `vega wallet key generate -w <WALLET_NAME> -p passphrase --home <WALLET_PATH>`
6. Import network config. Again, two ways to do that:
    1. Using URL: `vega wallet network import --from-url <CONFIG_URL> -f --home <WALLET_NAME>`.  `-f` flag overwrites the config if existed. Example: to import `fairground` network you should use: `vega wallet network import --from-url https://github.com/vegaprotocol/networks-internal/blob/main/fairground/vegawallet-fairground.toml`.
    2. Using file: If you want to import network for local vegacapsule network use this one: `vega wallet network import --force --from-file <CONFIG_FILE> --home <WALLET_PATH>`
7. If you need to obtain long live token for testing purposes you should do the following:
    1. Firstly initialise the api-token by command: `vega wallet api-token init --passphrase-file passphrase --home <WALLET_PATH>`
    2. Then generate the api-token for a single wallet: `vega wallet api-token generate --wallet-name <WALLET_NAME> --tokens-passphrase-file passphrase  --wallet-passphrase-file passphrase --home <WALLET_PATH>`
    3. Copy generated api-token and use it in your dAPP, tests or CI. It is the token that is normally obtained by `client.connect_wallet` request.
8. And now to start the service you need to use:
    1. For general purpose it is enough to use: `vega wallet service run -n <NETWORK_NAME> --home <WALLET_PATH>`.
    2.  In tests or CI more complex command should be used: `vega wallet service run -n <NETWORK_NAME> --load-tokens --tokens-passphrase-file passphrase --no-version-check --automatic-consent --home <WALLET_PATH>`.
     `--load-tokens` allows to use the token that was set up in previous steps. 
     `--no-version-check` allows to skip verification of network - if it’s alive and if wallet version matches network version. 
     `--automatic-consent` allows wallet to automatically accepts any requests and transactions that’s coming from connected apps.

And that’s it. The flow looks quite long, but you don’t really need to go through all the steps every time. If you don’t use it for CI or Testing purposes, you can easily skip few of the steps that relate to api-token. Also after you set up everything, you will probably only need to run `service run` command and update the binaries when the new version is released. Vega wallet HELP is pretty well documented. If you’re stuck with some command, just use e.g. `vega  wallet -h` or `vega wallet api-token generate -h` and you will receive all the information you need about the command. I hope you will find this guide helpful.

**Comment by radoslaw-szpiech** [comment]
I updated the content, to make it easier to understand and use by wider audience.
