### ISSUE TITLE
Spike: Investigate alternative ways to display REST Endpoints

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#431]
## The Spike

The structure of our API documentation is auto generated - the resulting navigation isn't easy to navigate or understand. This spike is to investigate what we'd need to do to move from our existing structure to something closer to the examples we've seen with [Stripe](https://stripe.com/docs/api/customers), where API endpoints are exposed in the navigation, and endpoint pages are flattened (?) to make it easier to find what you are looking for.

The outcome of this spike will be a list of tickets likely for core and docusaurus.

## Background 
<img width="1218" alt="Screenshot 2022-12-16 at 09 24 00" src="https://user-images.githubusercontent.com/46783148/208066263-b03dd701-ecd6-467c-bcbb-deeacf2757c7.png">

<img width="1509" alt="Screenshot 2022-12-16 at 09 18 46" src="https://user-images.githubusercontent.com/46783148/208065241-165ecf47-6447-4075-8719-db06b68a6905.png">

X-platform miro board : https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764540873973929&cot=14

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by candida-d** [comment]
The REST endpoints now come out of the protos grouped by topic, such as accounts, trades, governance, etc. I'd say while staying true to the framework we have and not hacking it up, this, plus the enhanced intro content, makes navigation and context better. 

If we get to a position where we have good alternatives and can retire auto-generated gRPC and GraphQL, then the sidebar accordion for REST can be kept expanded by default but for the time being that would be too noisy.
