### ISSUE TITLE
Add OpenAPI documentation of the wallet

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/documentation#484]
That would be nice for our user to have the equivalent of [this page](https://docs.vega.xyz/testnet/api/rest/explorer/block-explorer-list-transactions) for the wallet service API.

Link to the documentation:

https://raw.githubusercontent.com/vegaprotocol/vega/develop/wallet/service/openapi.json

**Comment by candida-d** [comment]
Bugs/problems that I'll need input from @edd on:
- Wallet API index page doesn't act as an index page
- REST HTTP files have broken formatting that puts all the copy in the front matter
- URL to view raw documentation from GH is broken in REST HTTP pages
