### ISSUE TITLE
Script for generating proposal templates

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/documentation#68]
For each proposal type we'd like an example of the json that a user you need to submit.
This to create a script that uses some schema to generate some examples.

Validation time stamps may be blank place holders or something else, but don't need to work (it is fair to expect the user to updates these).
Ideally the example would be commented to explain the types of information required on each field e.g. asset id for settlement asset. but this could be a future iteration.

Ideally would be generated on the build of the docs site and be discoverable to docs users in the proposals section.

# Tasks
- [x] Single Network parameter (multiple network param changes may come later)
- [x] New markets
- [x] Market change
- ~New asset~ _Waiting for 0.51.x so that Swagger/graphql/cmd all support this equally_ 
- ~Asset change~ _Waiting for 0.51.x so that Swagger/graphql/cmd all support this equally_
- [x] Freeform
- [x] Fix timestamps being submitted in milliseconds, not seconds
- [ ] Test proposals

**Comment by edd** [comment]
https://github.com/vegaprotocol/documentation/tree/spike/proposals-example-generation is where this work is going on

**Comment by edd** [comment]
@candida-d see also #79

**Comment by candida-d** [comment]
@edd I think this one is done now, and the follow-on ticket you linked to covers the additional work. Do you agree?

**Comment by edd** [comment]
It *could* be an error that @dexturr pointed out earlier - I have the time specified incorrectly, so the closing/opening dates for the auction are almost certainly invalid.

So:
- If the proposal was not signed by the wallet:
  - It could be a wallet version issue (but you'd see a note to update) 
  - itcould be a problem with the generated proposal
- If the wallet signed it, but it never showed up on the target network, that's maybe a problem with the generated proposal
- If you see it appear on the network but it's immediately rejected, it's probably the date problem
We'll find out next week!
