### ISSUE TITLE
Dark mode: Menu link styles inconsistent

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#70]
Some of the top level menu links in dark mode don't show up 

![image](https://user-images.githubusercontent.com/62548908/163154356-a65a75f0-45b5-46c3-996a-38860457f61a.png)

**Comment by candida-d** [comment]
related: https://github.com/vegaprotocol/documentation/issues/71

**Comment by gordsport** [comment]
Closing as this looks now to be resolved
