### ISSUE TITLE
Selected item in page nav invisible (same bg/fg colour)

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/documentation#71]
See screenshot - the selected item in the page navigaton links on the right is not visible (Firefox, Mac, dark mode)

<img width="1594" alt="Screenshot 2022-04-13 at 11 37 19" src="https://user-images.githubusercontent.com/1179257/163161965-24ab71c6-f312-4c2e-a379-784abea33e88.png">

**Comment by candida-d** [comment]
This is definitely still a problem, as seen here in dark mode https://docs.vega.xyz/docs/mainnet/grpc/vega/vega.proto#epochparticipation
