### ISSUE TITLE
Concepts: Add volume discount programme

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/documentation#722]
## The Chore

A volume discount programme is being introduced to Vega, we need to explain Vega's implementation.

## Tasks

- [ ] Describe Vega's implementation that enables the community to create a volume discount programme

## Additional details / background info
- Spec: https://github.com/vegaprotocol/specs/pull/1829 see https://github.com/vegaprotocol/specs/blob/9ae928fb95dfb511ae5e7a29c280ef0d9a8cf7b0/protocol/0083-VDPR-volume_discount_program.md
- Related to #719

**Comment by JonRay15** [comment]
Barney & Ramsey are doing drafts of this stuff ... so TBC if this ends up in Concepts
