### ISSUE TITLE
Update data node operator docs for archival nodes and add information on data compression

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/documentation#762]
# Feature overview

**In** the best interests of the protocol and its users it has been decided that the default retention for data nodes should be set to `--archival`. This is so that users can access all data from the data nodes as required. There has been concerns regarding the amount of disk space required for running an archival node therefore...
**We will** update the documentation to make the default set up `--archival` and also detail (or link to a readme) some instructions on how to use ZFS to lower the perceived barrier to using this compression  

## Core work
- [Make archival the default for data node retention](https://github.com/vegaprotocol/vega/issues/9562)
- [Increase Data Node NetworkHistory.Initialise.MinimumBlockCount default values](https://github.com/vegaprotocol/vega/issues/9549)

## Tasks
A checklist of the tasks that are needed to fully document the requested topic.

- [ ] update docs where needed to detail `--archival` as the default set up
- [ ] add data node operator recommendations on how to use ZFS

**Comment by wwestgarth** [comment]
Note that https://github.com/vegaprotocol/vega/issues/9562 made a breaking change to the options such that it is now `--mode=[archive|lite|standard]` with default `archive`. So while doing this ticket we can make sure we clean up and references to the old CLI args `--archive/--lite`.
