### ISSUE TITLE
Improve the successor market docs

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/documentation#853]
# Feature overview

One of the market makers returned the issue with successor market documentation. I think it would be good to write it ASAP:

```
> Hello, I am a bit confused by the successor market docs. I don't see the necessary fields in the examples
> Am I blind or are they missing?
> Also is it the same process for Perps? The decimals on the LINK market are a bit silly so I'm going to propose we close it and re-open it using the successor feature
> https://docs.vega.xyz/mainnet/tutorials/proposals/new-successor-market-proposal
> Also when we make a proposal for a successor market while the parent is active does this mean that the protocol duplicates our LP commitments or will thye automatically be withdrawn from the parent market at enactment time of the successor market?
```

## Tasks
A checklist of the tasks that are needed to document the requested topic fully.

- [ ] Test current documentation
- [x] Update docs
- [x] Make sure we create successor market on one of our internal docs

**Comment by edd** [comment]
@daniel1302 thanks for reporting this, it's now fixed. The fields were there in the past, but I removed them in another change by mistake. My fault, sorry for the confusion.
