### ISSUE TITLE
Set up versioning structure & test  

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#9]
Create the file structure for versioned markdown documentation. Might need some help from @ashleyvega if it's more complicated than it appears. 

https://docusaurus.io/docs/versioning

Make sure that it works as expected: links work, navigation shows up, navigation works. 

First version - restricted mainnet 

Auto-generated documentation will likely also need to be versioned but the current state of it means it probably comes later.

**Comment by ashleyvega** [comment]
- include pre-releases
- include last N releases
- for _old_ releases, only include latest patch ver
